server:
  port: 9091

spring:
  application:
    name: one-sink-source
  cloud:
    stream:
# -- Please refer to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-docs/src/main/asciidoc/overview.adoc#binding-properties
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
#          autoCreateTopics: true          
#          autoAddPartitions: true
#          configuration:
#            security:
#              protocol: SASL_PLAINTEXT
#          autoCreateTopics: true          
#          autoAddPartitions: true
#          headers:
#            - X-B3-TraceId
#            - X-B3-SpanId
#            - X-B3-Sampled
#            - X-B3-ParentSpanId
#            - X-Span-Name
#            - X-Span-Export
#            - X-Process-Id
#            - spanId
#            - spanSampled
#            - spanProcessId
#            - spanParentSpanId
#            - spanTraceId
#            - spanName
#            - messageSent
      bindings:
        input:
          group: messages-group-a
          destination: sink-source-topic
        output:
          group: messages-group-a
          destination: sink-source-topic
#        bindings:
#            liveSource:
#                binder: kafka
#                consumer:
#                    headerMode: raw
#                    autoCommitOffset: true
#                destination: topic_example_name
